language: generic
sudo: required
# tell Travis we need a copy of docker running
services:
  - docker

# build an image using Dockerfile.dev
before_install:
  - docker build -t romul3003/docker-react -f Dockerfile.dev .

# tell Travis how to run our test suite
script:
  - docker run -e CI=true romul3003/docker-react npm run test
