version: '3'

# list of different services or containers
services:
  # name of service
  web:
    stdin_open: true # fix, if cra fails
    build:
      # all files and folders from the same directory
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - "3000:3000"
    volumes:
    # do not try to map a folder up against app node_modules inside the container
    - /app/node_modules
    # map that folder outside the container into the app folder inside
    - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
    - /app/node_modules
    - .:/app
    # override command npm run start
    command: ["npm", "run", "test"]
